#spring:
#  application:
#    name: orderflow
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    database: mysql
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#springdoc:
#  swagger-ui:
#    path: /swagger-orderflow-ui/
#    # 각 API 그룹 표시 순서 path-query-response 순
#    groups-order: desc
#    tags-sorter: alpha          #tag 알파벳 순 정렬
#    operations-sorter: method   #delete-get-patch-post-put 순
#    disable-swagger-default-url: true
#    display-request-duration: true
#  api-docs:
#    path: /api-docs
#  default-consumes-media-type: application/json
#
#  #노출되는 url Controller
#  paths-to-match:
#    - /api/**
spring:
  application:
    name: orderflow

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-orderflow-ui/
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json

  paths-to-match:
    - /api/**

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
