spring:
  application:
    name: orderflow

  datasource:
    url: jdbc:mysql://localhost:3306/orderflow
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

