spring:
  application:
    name: orderflow

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
      
  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-orderflow-ui/
    # 각 API 그룹 표시 순서 path-query-response 순
    groups-order: desc
    tags-sorter: alpha          #tag 알파벳 순 정렬
    operations-sorter: method   #delete-get-patch-post-put 순
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json

  #노출되는 url Controller
  paths-to-match:
    - /api/**

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2

#QR_API
qr:
  code:
    api: "https://api.qrserver.com/v1/create-qr-code/?size=400x400&data="

openai:
  model: gpt-4o
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions

jwt:
  secret: '4oCYc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXTigJkK'

coolsms:
  api:
    key: NCSRH6Q6ILREH2QF
    secret: C15D2OCMIHBW8UQ2ARMP2FBDAH8D0ZYX